00 - Resource Deployment/README.md
02 - Web UI Template/CognitiveSearch.Template/CognitiveSearch.UI/CognitiveSearch.UI.csproj

updating readme and package version

updating readme and package version

---

02 - Web UI Template/CognitiveSearch.Template/CognitiveSearch.UI/Views/Shared/_Layout.cshtml
03 - Data Science and Custom Skills/AML Custom Skill Template/01_Train_AML_Model.ipynb
03 - Data Science and Custom Skills/AML Custom Skill Template/02_Deploy_AML_Custom_Skill.ipynb

1.	Updated model output to return a category rather than a number
2.	Standardized some variable names and comments
3.	Fixed spelling of scikit-learn

 standardized variable names and updated model output

---

README.md

The link on the readme to the WebUI template readme is broken
* ...
```
[ ] Bugfix
[ ] Feature
[x ] Documentation content changes
```
```
cd [repo-name]
npm install
```
```
```
* ...
clicking the link to the web UI readme on the main readme file navigates properly

Brokenlink

---

00 - Resource Deployment/deploy.ps1

Adds a missing dependency to the deployment script.

Add cognitive services resource provider to the deploy script.

---

02 - Web UI Template/CognitiveSearch.UI/Search/SearchModel.cs

Clicking on a result won't allow the details view to load if the id of the document is missing from the results
* ...
```
[ ] Yes
[ X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Code style update (formatting, local variables)
```
```
cd [repo-name]
npm install
```
```
```
* ...

Add "id" to the returned fields as needed by UI

---

00 - Resource Deployment/deploy.ps1
02 - Web UI Template/CognitiveSearch.UI/CognitiveSearch.UI.csproj
02 - Web UI Template/CognitiveSearch.UI/Search/DocumentResult.cs
02 - Web UI Template/CognitiveSearch.UI/Search/DocumentSearchClient.cs
02 - Web UI Template/CognitiveSearch.UI/Search/FacetGraphGenerator.cs
02 - Web UI Template/CognitiveSearch.UI/Search/SearchSchema.cs
02 - Web UI Template/CognitiveSearch.UI/wwwroot/js/tags.js

* Updating deployment script to leverage new AZ Powershell module rather than AzureRM module
* Updating to the latest azure search sdk
* improved error handling
* updates so complex types won't break the UI
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[X] Feature
[X] Refactoring (no functional changes, no api changes)
```
* Clone repo
* Navigate to resource deployment folder
* Run:
```
./deploy.ps1
```
* Create an index with complex types
* Update appsettings.json
* Run the UI
* resource group deploys successfully
* UI works with complex types

Updating to latest Azure Search SDK & Updating Script to AZ PowerShell

---

industry-solutions/journalism/projectida/readme.md
industry-solutions/journalism/readme.md

I am getting the structure setup for project IDA. 
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe:
```
Setup
```
NA
```
NA
NA
This is the first check in of getting project IDA up and running.

Adding the root level projectida folder and readme file.

---

01 - Search Index Creation/Cognitive Search Pipeline APIs.postman_collection.json
01 - Search Index Creation/Cognitive Search Pipeline Environment.postman_environment.json

fixing postman env file
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```

adding correct postman env file

---

README.md

* fix typos
* reduce dependence on images and add alt text (for accessibility)
* use active voice
* use doc-style formatting and grammar rules
* add links where helpful
* remove redundant license content
```
[ ] Yes
[X ] No
```
```
[ ] Bugfix
[ ] Feature
[ X] Documentation content changes
```
```
cd [repo-name]
npm install
```
```
```
* ...

Pafarley edits

---

02 - Web UI Template/README.md

* Fixes a spelling error
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Documentation content changes
```
```
cd [repo-name]
npm install
```
```
```
* ...

Fixed spelling error

---

02 - Web UI Template/CognitiveSearch.UI/Search/SearchModel.cs

* Adding in check to validate a field exists in the index to prevent errors
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```

Adding in check to validate a field exists in the index to prevent errors

---

02 - Web UI Template/CognitiveSearch.UI/wwwroot/js/results.js

This PR adds zoom controls to the newly added map control
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[x] Feature
```

Add zoom control to maps

---

workshops/Module 0.md

Updating SAS Token

---

02 - Web UI Template/CognitiveSearch.UI/CognitiveSearch.UI.csproj
02 - Web UI Template/CognitiveSearch.UI/Controllers/HomeController.cs
02 - Web UI Template/CognitiveSearch.UI/Controllers/StorageController.cs
02 - Web UI Template/CognitiveSearch.UI/Search/DocumentResult.cs
02 - Web UI Template/CognitiveSearch.UI/Search/DocumentSearchClient.cs
02 - Web UI Template/CognitiveSearch.UI/Search/FacetGraphGenerator.cs
02 - Web UI Template/CognitiveSearch.UI/Search/SearchSchema.cs
02 - Web UI Template/CognitiveSearch.UI/wwwroot/js/details.js
02 - Web UI Template/CognitiveSearch.UI/wwwroot/js/results.js

Upgrading SDKs to Track 2

---

02 - Web UI Template/CognitiveSearch.UI/CognitiveSearch.UI.csproj
02 - Web UI Template/CognitiveSearch.UI/Controllers/HomeController.cs
02 - Web UI Template/CognitiveSearch.UI/Controllers/StorageController.cs
02 - Web UI Template/CognitiveSearch.UI/Search/DocumentResult.cs
02 - Web UI Template/CognitiveSearch.UI/Search/DocumentSearchClient.cs
02 - Web UI Template/CognitiveSearch.UI/Search/FacetGraphGenerator.cs
02 - Web UI Template/CognitiveSearch.UI/Search/SearchSchema.cs

Change search and storage blob package track1 to track2

Change search and storage blob track1 to track2

---

02 - Web UI Template/CognitiveSearch.UI/wwwroot/js/facets.js

* Existing code doesn't remove the right facet value when there are multiple values, the last value always gets removed which is incorrect.
```
[ ] Yes
[x ] No
```
```
[x ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

Update RemoveFilter function within facets.js

---

02 - Web UI Template/README.md

Update README.md for custom skill template

---

02 - Web UI Template/CognitiveSearch.UI/Controllers/StorageController.cs

Managing file content when uploading a new file to the blob storage for indexing. This solves an issue with pdf which are downloaded instead of opening an in-browser visualization when the blob content type is set to application/octet-stream
```
[ ] Yes
[x ] No
```
```
[ ] Bugfix
[x ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

managing file content type in upload functionality

---

workshops/Module 7.md

Update to azs-playground medical-demo connection string with rotated password and fixed error in table name
```
[ ] Yes
[x] No
```
```
[x] Bugfix - found a bug in the table name, plus rotated the reader account password so the old password is broken.  
[ ] Feature
[] Other... Please describe: 
```
```
cd [repo-name]
npm install
```
```
```
* Create data source still works
* Running the indexer still works

Update to azs-playground medical-demo connection string with rotated password

---

README.md

Fixing bootcamp link

---

02 - Web UI Template/CognitiveSearch.UI/CognitiveSearch.UI.csproj
02 - Web UI Template/CognitiveSearch.UI/Controllers/HomeController.cs
02 - Web UI Template/CognitiveSearch.UI/Models/SearchResultViewModel.cs
02 - Web UI Template/CognitiveSearch.UI/Search/DocumentResult.cs
02 - Web UI Template/CognitiveSearch.UI/Search/DocumentSearchClient.cs
02 - Web UI Template/CognitiveSearch.UI/Views/Home/Search.cshtml
02 - Web UI Template/CognitiveSearch.UI/appsettings.json
02 - Web UI Template/CognitiveSearch.UI/wwwroot/css/site.css
02 - Web UI Template/CognitiveSearch.UI/wwwroot/js/details.js
02 - Web UI Template/CognitiveSearch.UI/wwwroot/js/facets.js
02 - Web UI Template/CognitiveSearch.UI/wwwroot/js/results.js
02 - Web UI Template/CognitiveSearch.UI/wwwroot/js/search.js
02 - Web UI Template/CognitiveSearch.UI/wwwroot/js/tags.js
02 - Web UI Template/README.md

* ...
* Added semantic query support
* Added answer support for semantic query
* Added toggle for semantic support
* Added scroll bar for facets
* Updated SDK to 11.4.0-beta for new semantic config
```
[ ] Yes
[X ] No
```
```
[ ] Bugfix
[X] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

semantic search support 

---

00 - Resource Deployment/SearchAssets.ps1
azuredeploy.json

* Added configuration for deploy Docker image of Web UI in the Azure one-click deployment button
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[x] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

added config to docker image for web-ui deploy

---

00 - Resource Deployment/README.md
00 - Resource Deployment/deploy.ps1

*  Fix current code to allow Cognitive Services account to be created after agreeing to RAI and Face Legal Terms 
```
[ ] Yes
[X ] No
```
What kind of change does this Pull Request introduce? Fix to allow Cognitive Services account to be created after agreeing to RAI and Face Legal Terms 
```
[X ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* Run .\deploy.ps1

Giabranch quick fixes

---

README.md

Fix broken deploy script link in documentation 
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x ] Documentation content changes
```
Deploy script link

Fix deploy script link

---

00 - Resource Deployment/README.md
01 - Search Index Creation/README.md
02 - Web UI Template/README.md
03 - Data Science and Custom Skills/README.md
04 - Reporting/README.md
README.md
workshops/Module 0.md
workshops/Module 1.md
workshops/Module 3.md
workshops/Module 4.md
workshops/Module 5.md
workshops/Module 7.md
workshops/README.md

Rebranding Azure Cognitive Search to Azure AI Search
```
[ ] Yes
[x ] No
```
```
[ ] Bugfix
[ ] Feature
[x ] Documentation content changes
```

Rebranding to Azure AI Search
